---
- hosts: localhost
  become: true
  tasks:
    - name: Create directory for openshift docker-registry public key
      file:
        path: /etc/docker/certs.d/docker-registry-default.apps.stackroute.io/
        state: directory
        recurse: yes
    - name: Download docker-registry crt
      get_url:
        url: https://s3.ap-south-1.amazonaws.com/openshift-public/ca.crt
        dest: /etc/docker/certs.d/docker-registry-default.apps.stackroute.io/ca.crt
        checksum: sha256:a56366f1cf458821d7ecd1bb8e1ba93ccbaaa223c0f893aa61bdba51d3eb3e49
